version: '3.8'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft_server
    ports:
      - "25565:25565"
    volumes:
      - minecraft_data:/app
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  minecraft_data:
    driver: local
