name: Homeplugin
version: '1.0-SNAPSHOT'
main: br.github.hebertfsoares.homeplugin.Homeplugin
api-version: '1.21'
description: Um plugin para definir e teletransportar para homes
commands:
  sethome:
    description: Define uma home
  home:
    description: Teleporta para a home
